language: python
python:
    - "3.6"
sudo: enabled
env:
  - INFLUXDB_VER=1.7.4
addons:
  apt:
    packages:
    - wget
before_install:
    - mv example_config.py config.py
install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install pytest==3.6 pytest-cov
    - mkdir -p "influxdb_install/${INFLUXDB_VER}"
    - if [ -n "${INFLUXDB_VER}" ] ; then wget "https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VER}_amd64.deb" ; fi
    - if [ -n "${INFLUXDB_VER}" ] ; then dpkg -x influxdb*.deb "influxdb_install/${INFLUXDB_VER}" ; fi
script:
    - export "INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/${INFLUXDB_VER}/usr/bin/influxd"
    - sudo service influxdb start
    - pytest --cov-report xml --cov=app -m "not integration_test"
after_succes:
    - codecov
branches:
  only:
  - master
