language: python
python:
    - "3.6"
sudo: enabled
before_install:
    - mv example_config.py config.py
    - sudo apt install influxdb
install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install pytest==3.6 pytest-cov
script:
    - pytest --cov-report xml --cov=app -m "not integration_test"
after_succes:
    - codecov
branches:
  only:
  - master
